<p>El objeto de esta hoja es mostrar las mejoras en eficiencia , enormes, que se obtienen al utilizar listas y matrices de numpy en lugar de las habituales de Sage.&nbsp; Esto se debe a que el c&oacute;digo de numpy est&aacute; muy optimizado.</p>
<p>Comenzamos generando dos listas de cien millones de n&uacute;meros aleatorios entre cero y uno, calculando el cuadrado de cada&nbsp;&nbsp; elemento&nbsp; y sumando&nbsp; los resultados, primero en la forma normal en Sage y luego usando numpy:</p>

In [1]:
def cuad(x):
    return x*x
def suma_cuadrados():
    L = [random() for muda in xsrange(10^7)]
    return sum(map(cuad,L))

In [2]:
time suma_cuadrados()

3333258.0607009917
Time: CPU 7.80 s, Wall: 7.80 s

In [3]:
import numpy as np
np.random.seed([763829])
time A = np.random.rand(10000000)
time sum(A*A)

Time: CPU 0.18 s, Wall: 0.18 s
3332849.8862028224
Time: CPU 0.07 s, Wall: 0.07 s

<p>Tomamos ahora $10^8$ n&uacute;meros aleatorios todav&iacute;a con tiempos muy bajos:</p>

In [4]:
import numpy as np
np.random.seed([763829])
time A = np.random.rand(100000000)
time sum(A*A)

Time: CPU 1.52 s, Wall: 1.53 s
33331946.820564572
Time: CPU 0.48 s, Wall: 0.49 s

<p>Una vez generada la lista del tipo numpy $C$, podemos aplicar una funci&oacute;n, como el logaritmo,&nbsp; a todos los elementos de la lista mediante $log(C)$:</p>

In [5]:
import numpy as np
np.random.seed([763829]) 
C = np.random.rand(100000000)
print sum(log(C))
print prod(log(C))

-100009700.132
0.0

<p>Pasamos ahora de listas de numpy a matrices de numpy:</p>

In [6]:
A = np.random.rand(2,2) #Una matriz 2x2 con entradas numeros aleatorios
print A
B = A.dot(A) #B es su cuadrado. El producto de A por B es A.dot(B)
print B

[[ 0.79881494  0.96851941]
 [ 0.90952275  0.89096117]]
[[ 1.51899576  1.63658096]
 [ 1.53688982  1.67470224]]

<p>Queremos elevar una matriz de numpy a un exponente, y para eso usamos la funci&oacute;n recursiva general para elevar a exponentes en anillos:</p>

In [7]:
def potencia(A,n):
    m = A.shape[0]
    if n==0:
        return np.identity(m)
    elif n%2 == 0:
        B = potencia(A,n/2)
        return B.dot(B)
    else:
        B = potencia(A,(n-1)/2)
        return A.dot(B.dot(B))

In [8]:
potencia(A,100)

array([[  6.77077080e+24,   7.33831143e+24],
       [  6.89130354e+24,   7.46894748e+24]])

<p>La notaci&oacute;n $A^n$ no sirve para matrices de numpy, porque para ellas $A*A$ es el producto elemento a elemento, que no es igual al producto de matrices. Es por eso que definimos la funci&oacute;n potencia usando como producro de matrices&nbsp; $A.dot(A)$.</p>

In [9]:
A^(100)

array([[  1.75637856e-10,   4.08162191e-02],
       [  7.60951334e-05,   9.68004685e-06]])

In [10]:
C = matrix(RR,[[ 0.79881494,0.96851941],[0.90952275,0.89096117]])

In [11]:
C^(100)

[6.77077042398315e24 7.33831108240865e24]
[6.89130316554811e24 7.46894713973031e24]

In [12]:
import numpy as np
D = np.random.rand(500,500)

In [13]:
time E = D.dot(D)

Time: CPU 0.03 s, Wall: 0.05 s

In [14]:
time E_inv = np.linalg.inv(E)

Time: CPU 0.05 s, Wall: 0.05 s

<p>Repetimos ahora los c&aacute;lculos usando una matriz similar pero de Sage, con las operaciones habituales de Sage. Obs&eacute;rvese la diferencia espectacular en los tiempos, debido a que los c&oacute;digos que utiliza numpy est&aacute;n muy optimizados.&nbsp; </p>

In [15]:
F = matrix(RR,500,500,[random() for muda in srange(250000)])

<p>Su cuadrado:</p>

In [16]:
time G = F*F

Time: CPU 64.42 s, Wall: 64.42 s

<p>La inversa del cuadrado de $F$:</p>

In [17]:
time G_inv=G.inverse()

Time: CPU 80.20 s, Wall: 80.24 s